CREATE TABLE users(
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	pass VARCHAR(300) NOT NULL,
	role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
	active TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB;